package dbaas

const (
	// AppNameLabelKey identifies the chart that rendered a database, and is what
	// distinguishes an SPX-managed database from any other CloudNativePG cluster
	// that may live in the namespace.
	AppNameLabelKey = "app.kubernetes.io/name"

	// ChartName is the value AppNameLabelKey carries for DBaaS resources.
	ChartName = "sfs-dbaas"

	// appSecretSuffix is the suffix CloudNativePG appends to the cluster name for
	// the application credentials Secret it generates.
	appSecretSuffix = "-app"

	// readWriteServiceSuffix is the suffix of the service pointing at the primary.
	readWriteServiceSuffix = "-rw"

	// readOnlyServiceSuffix is the suffix of the service load-balancing the replicas.
	readOnlyServiceSuffix = "-ro"

	// PostgresPort is the port a PostgreSQL database listens on.
	PostgresPort = 5432
)

// Keys of the application credentials Secret generated by CloudNativePG.
const (
	secretKeyUsername = "username"
	secretKeyPassword = "password"
	secretKeyDatabase = "dbname"
)
